### ISSUE TITLE
Dotnet file extension is undefined

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/sdk-example-editor#27]
**Describe the bug**
Adding `dotnet-standard` examples and downloading the file results in a zip with the updated API definition and an example folder. in the dotnet-standard folder the files have `undefined` as the extension.

![dotnet-examples-undefined-extension](https://user-images.githubusercontent.com/4381558/58641914-c8c28100-82c1-11e9-94e8-a71a16e3910c.PNG)

**To Reproduce**
1. Add a new langauge `dotnet-standard`
2. Add an example
3. Download the api definition
4. See the example files for dotnet-standard has the extension `undefined`

**Expected behavior**
The extension for C# files is `.cs`

**Additional context**
The ID team asked that we use `dotnet-standard` so they don't have to update their CLI.

**Comment by germanattanasio** [comment]
I think you need to use `dotnet` or `c#`. In any case I added `dotnet-standard`
