### ISSUE TITLE
Support Yaml

### ISSUE THREAD

**Issue by sefuhrer** [watson-developer-cloud/sdk-example-editor#44]
**Is your feature request related to a problem? Please describe.**
Yes, many teams are authoring in YAML. YAML files do not open in the tool. They can easily convert to JSON save and convert back but built in support would be good. 

**Describe the solution you'd like**
I can open a YAML file in the tool and author and save to YAML.

**Describe alternatives you've considered**
convert YAML to JSON in advnace, save, convert back :)

**Additional context**

**Comment by germanattanasio** [comment]
This sounds like a good idea @sefuhrer. We will try to do it tomorrow during Think Friday.

**Comment by germanattanasio** [comment]
@lpatino10 if you get some time next week can you look at it. I didn't get the time today 😢

**Comment by lpatino10** [comment]
Yep, I can take a look!

**Comment by lpatino10** [comment]
Sorry for the delay @sefuhrer, but it's out and working now. Thanks again for using the tool!
