### ISSUE TITLE
UI can't handle changes to multiple examples for one method

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/sdk-example-editor#50]
**Describe the bug**
The UI prevents me from changing the 2nd example of a method with 2 examples

**To Reproduce**
1. Load visual-recognition-v3.json
2. Load any language
3. Scroll to the `Classify images` method
4. Make a change to the first example
5. Make a change to the 2nd example. Notice that it doesn't change, and the cursor returns to the first example

**Screenshots**
![2019-09-25_15-43-08 (1)](https://user-images.githubusercontent.com/8194208/65634186-b1637e00-dfab-11e9-969f-1b2cf3b6edc9.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by lpatino10** [comment]
Yeah this one's definitely problematic 😕  Will be first on my list to fix for this project.
