### ISSUE TITLE
Wrap code so that editor window is wider

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/sdk-example-editor#51]
It's sometimes difficult to work with the left editor because the right code isn't wrapping and the window is too wide. Most often in Curl, but also an issue in other languages.

**Describe the solution you'd like**
Wrap the code so that the 2 panes remain equally sized, or allow resizing of either side. 

![image](https://user-images.githubusercontent.com/8194208/65693848-ed95ed80-e042-11e9-9f10-4626389226d6.png)

**Comment by lpatino10** [comment]
Good feedback. The UI could definitely use some more polish!

Thanks for taking the time to submit these @SirSpidey
