### ISSUE TITLE
backslash is stripped from examples

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/sdk-example-editor#53]
**Describe the bug**
The first backslash `\` of a request example is stripped and cannot be added. I think it is stripped as soon as the file is opened in the editor, rendering all those examples incorrect.

**To Reproduce**
1. Open a definition file in YAML
2. Paste in this example:
    ```
    curl -k -X PUT -H "Authorization: Bearer {token}" -H "cache-control: no-cache" -d "{\"description\":\"{role_description}\",\"permissions\":\"{permissions}\"}" "https://{cpd_cluster_host}{:port}/icp4d-api/v1/roles/{role_name}"
    ````
    Note that the `description` in the `-d` payload is escaped.
3. Note that the first escaped quotation mark in description is stripped so that the output is 
    ```
    curl -k -X ... -d "{"description\":\"{role_description}\",...}
    ```
4. Try to manually enter the `\`. You can't

**Expected behavior**
escaped characters are left as is

**Screenshots**

![image](https://user-images.githubusercontent.com/8194208/66422510-d0183a80-e9d7-11e9-8fc0-2850cc9ac329.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by germanattanasio** [comment]
Can you use `'` rather than `"`?

**Comment by germanattanasio** [comment]
```
curl -k -X PUT -H "Authorization: Bearer {token}" -H "cache-control: no-cache" -d '{ "description": "{role_description}", "permissions": "{permissions} "}' 'https://{cpd_cluster_host}{:port}/icp4d-api/v1/roles/{role_name}'
```

**Comment by SirSpidey** [comment]
We use this syntax (and have for a while) so that it works on both Linux-based and Windows OSs. Tools should support what we want to document, not the other way around ;-)

**Comment by germanattanasio** [comment]
So you are saying that my example doesn't work in Windows?

**Comment by germanattanasio** [comment]
I was just suggesting a better way to do the examples that will solve the problem
