### ISSUE TITLE
Add support for extracted request examples

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/sdk-example-editor#55]
Stub issue of https://github.ibm.com/watson/developer-experience/issues/8150 about adding support for file that includes only the paths and `x-sdk-operations` request examples.

**Comment by germanattanasio** [comment]
Fixed in f944fa0c12e62b8625e08705b9bbc8406645f96a

**Comment by germanattanasio** [comment]
@all-contributors please add @germanattanasio for code, tests, and docs

**Comment by germanattanasio** [comment]
@all-contributors please add @lpatino10  for code, and docs
